# apiVersion: v1
# kind: Namespace
# metadata:
#   name: {{ .Values.Namespacename }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: Backend
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.Namespacename }}

spec:
  replicas: {{ .Values.Deployment.ReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.Deployment.RollingUpdate.MaxSurge }}
      maxUnavailable: {{ .Values.Deployment.RollingUpdate.MaxUnavailable }}
  {{- if .Values.Deployment.Affinity }}
  affinity:
    {{- if .Values.Deployment.Affinity.PodAffinity }}
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: {{ .Values.Deployment.Affinity.PodAffinity.Key }}
            operator: In
            values: 
            {{- toYaml .Values.Deployment.Affinity.PodAffinity.Values | nindent 20 }}
    {{- end }}
    {{- if .Values.Deployment.Affinity.PodAntiAffinity }}
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: {{ int .Values.Deployment.Affinity.PodAntiAffinity.Weight }}
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: {{ .Values.Deployment.Affinity.PodAntiAffinity.Key }}
              operator: In
              values:
              {{- toYaml .Values.Deployment.Affinity.PodAntiAffinity.Values | nindent 20 }}
          topologyKey: {{ .Values.Deployment.Affinity.PodAntiAffinity.TopologyKey }}
    {{- end }}
    {{- if .Values.Deployment.Affinity.NodeAffinity }}
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: {{ int .Values.Deployment.Affinity.NodeAffinity.Weight }}
        preference:
          labelSelector:
            matchExpressions:
            - key: 
                {{ .Values.Deployment.Affinity.NodeAffinity.Key | quote }}
              operator: In
              values:
              {{- toYaml .Values.Deployment.Affinity.NodeAffinity.Values | nindent 20 }}
    {{- end }}
    {{- if .Values.Deployment.Affinity.NodeAntiAffinity }}
    nodeAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: {{ int .Values.Deployment.Affinity.NodeAntiAffinity.Weight }}
        nodeAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: {{ .Values.Deployment.Affinity.NodeAntiAffinity.Key }}
              operator: In
              values:
              {{- toYaml .Values.Deployment.Affinity.NodeAntiAffinity.Values | nindent 20 }}
    {{- end }}
  {{- end }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.Deployment.Image.Name }}:{{ .Values.Deployment.Image.Tag }}
        imagePullPolicy: {{ .Values.Deployment.Image.PullPolicy }}
        name: {{ .Release.Name }}
        ports:
        - name: {{ .Values.Deployment.Port.Name }}
          containerPort: {{ .Values.Deployment.Port.ContainerPort }}
        resources:
          limits:
            cpu: {{ .Values.Deployment.Resources.Limits.Cpu }}
            memory: {{ .Values.Deployment.Resources.Limits.Memory }}
          requests:
            cpu: {{ .Values.Deployment.Resources.Requests.Cpu }}
            memory: {{ .Values.Deployment.Resources.Requests.Memory }}
        # volumeMounts: 
        #   - name: persistent-storage
        #     mountPath: /var/lib/storage
      volumes: 
        - name: persistent-storage
          persistentVolumeClaim: 
            claimName: ebs-pv-claim

---