apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.Namespacename }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Deploymentname }}
spec:
  replicas: {{ .Values.Deployment.ReplicaCount}}
  selector:
    matchLabels:
      {{- toYaml .Values.matchLabels| nindent 6 }}
  
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels| nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.containers.image }}
        imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
        name: {{ .Values.containers.name }}
        ports:
        - name: {{ .Values.Deployment.Port.Name }}
          containerPort: {{ .Values.Deployment.Port.ContainerPort }}
