apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Ingressname }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.IngressClassname }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ .Values.Service.Servicename }}
                port: 
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  namespace: ingress-nginx
  name: ingress-alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ingress-nginx-controller
              port:
                number: 80