apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Ingress.Ingressname }}
  annotations:
    {{- toYaml .Values.annotations| nindent 4 }}
    
spec:
  ingressClassName: {{ .Values.Ingress.IngressClassname }}
  rules:
    - host: {{ .Values.Ingress.host }}
      http:
        paths:
          - path: {{ .Values.Ingress.path }}
            pathType: {{ .Values.Ingress.pathType }}
            backend:
              service: 
                name: {{ .Release.Name }}-service
                port: 
                  number: {{ .Values.Service.Port }}
    
  

                
