Namespacename: qa

Deployment:
  ReplicaCount: 2
  name : crud-deployment
  Image:
    Name: 666697415673.dkr.ecr.us-east-1.amazonaws.com/spring
    Tag: V9
    PullPolicy: Always
  Port:
    Name: http
    ContainerPort: 8080
      
  RollingUpdate:
    MaxSurge: 25%
    MaxUnavailable: 25%
  Resources:
    Limits:
      Cpu: 400m
      Memory: 400Mi
    Requests:
      Cpu: 400m
      Memory: 400Mi

Service:
  Type: ClusterIP
  Port: 80
  TargetPort: 8080


Ingress:
  Ingressname: crud
  IngressClassname: nginx-external
  path: /
  pathType: Prefix
  
  
annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /     
        
