Namespacename: crud

labels:
  app.kubernetes.io/name: crud
 
matchLabels:
  app.kubernetes.io/name: crud
  
selector:
  app.kubernetes.io/name: crud


Deployment:
  ReplicaCount: 2
  name : crud-deployment
  Port:
    Name: http
    ContainerPort: 8080
containers:
  name: crud
  image: '${registry}:V${BUILD_NUMBER}'
  imagePullPolicy: Always

Service:
  ServiceName: crud-service
  Type: clusterIP
  Port: 80
  TargetPort: 8080

Ingress:
  
  Ingressname: crud-ingress
  IngressClassname: nginx-external


  
annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /