Namespacename: crud

Deploymentname: crud-deployment

Servicename: crud-service

Ingressname: crud-ingress

labels:
  app.kubernetes.io/name: crud
 
matchLabels:
  app.kubernetes.io/name: crud
  
selector:
  app.kubernetes.io/name: crud

containers:
  name: crud
  image: '${registry}:V${BUILD_NUMBER}'
  imagePullPolicy: Always
  
#annotations:
 # nginx.ingress.kubernetes.io/rewrite-target: /