apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Ingressname }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-external
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ .Values.Servicename }}
                port: 
                  number: 80