apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pv-claim
  namespace: qa
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 0.5Gi